name: Code Analysis (PMD)

on:
  pull_request:
  push:
  workflow_dispatch:

jobs:
  dupe_check:
    name: Check for Duplicate Workflow Run
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v3.4.0
        with:
          concurrent_skipping: same_content
          do_not_skip: '["pull_request", "workflow_dispatch", "schedule"]'

  run-analysis:
    name: Run PMD Static Code Analysis
    needs:
      - dupe_check
    if: needs.dupe_check.outputs.should_skip != 'true'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-pmd-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-build-
      - name: Setup JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: zulu
          java-version: 8
      - name: Install Test Support
        run: mvn clean install -f solace-integration-test-support/ -DskipTests
      - name: Run static code analysis
        run: mvn clean compile pmd:check -Dformat=net.sourceforge.pmd.renderers.SarifRenderer
      - name: Upload Test Artifacts
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: Code Analysis (PMD) Results
          path: |
            beam-sdks-java-io-solace/target/pmd.xml
            beam-sdks-java-io-solace/target/pmd.net.sourceforge.pmd.renderers.SarifRenderer
            beam-sdks-java-io-solace/target/pmd/
            beam-sdks-java-io-solace/target/site/pmd.html
      - name: Upload SARIF file
        if: success() || failure()
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: beam-sdks-java-io-solace/target/pmd.net.sourceforge.pmd.renderers.SarifRenderer
